name: markdownlint
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - name: yarn install
        run: |
          yarn install
      - name: yarn markdownlint
        run: |
          yarn lint:md
