name: markdownlint
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - name: yarn install
        run: |
          yarn install
      - name: markdownlint
        run: |
          git fetch
          DIFF_FILES=$(git diff remotes/origin/${{ github.base_ref }}..HEAD --diff-filter=ACDMR --name-only "*.md")

          DIFF_EXISTS="false"
          for f in $DIFF_FILES; do
            MDLINT_OUT=$(npx markdownlint $f)
            if [ -n "$MDLINT_OUT" ]; then
              echo "$MDLINT_OUT"
              DIFF_EXISTS="true"
            fi
          done

          if [ "$DIFF_EXISTS" = "true" ]; then
            echo "::error::!!markdownlint errors detected!!"
            exit 1
          fi
